default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: <%= ENV['DATABASE_URL'] %>
  # host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  
test:
  <<: *default

production:
  <<: *default