default: &default
  adapter: mysql
  pool: 5
  timeout: 5000
  database: <%= ENV['DATABASE'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  
test:
  <<: *default

production:
  <<: *default